.TH "rtl_biast" 1 "2.0.3" RTL-SDR "User Commands"
.SH NAME
rtl_biast \- a tool for turning the bias tee or any GPIO on and off
.SH SYNOPSIS
.B  rtl_biast [OPTIONS]
.SH DESCRIPTION
Switch the bias tee power supply of an RTL2832 based receiver on or off.
Many receivers provide a bias tee to feed DC power out over the antenna
connector, for example to supply an external low noise amplifier or an
active antenna.
.LP
The bias tee is driven by GPIO 0 of the RTL2832. Receivers that wire it
to a different pin, or that expose further GPIOs, can be controlled with
the -g option.
.LP
The setting is not reset when rtl_biast exits. The bias tee stays in the
state it was left in until it is switched off again, either by another
call to rtl_biast or by a client program that disables it explicitly.
.SH OPTIONS
.IP "-d device_index or serial (default: 0)"
.IP "-b bias_on (default: 0)"
.IP "-g GPIO select (default: 0)"
.SH EXAMPLES
.IP "To turn the bias tee of the first device on, call"
 rtl_biast -d 0 -b 1
.IP "To turn it off again, call"
 rtl_biast -d 0 -b 0
.IP "To switch GPIO 1 instead of the bias tee, call"
 rtl_biast -d 0 -g 1 -b 1
.SH SEE ALSO
RTL-SDR wiki documentation:
.B http://sdr.osmocom.org/trac/wiki/rtl-sdr
.LP
Other rtl-sdr programs:
.sp
rtl_adsb(1), rtl_eeprom(1), rtl_fm(1), rtl_power(1), rtl_sdr(1), rtl_tcp(1), rtl_test(1)
.SH AUTHOR
This manual page was written for the osmocom rtl-sdr project.
.SH COPYRIGHT
Copyright (c) 2012 Steve Markgraf <steve@steve-m.de>
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
